let css = "";

let hoursHtml = "";

for (let i = 0; i < 12; i++) {
  css += `
.hour-tick-${i} {
  transform: rotate(${i * 30}deg);
}
`;
  hoursHtml += `  <div class="hour-tick hour-tick-${i}"></div>
`;
}

let minutesHtml = "";

for (let i = 0; i < 60; i++) {
  if (i % 5 === 0) continue;

  css += `
.minute-tick-${i} {
  transform: rotate(${i * 6}deg);
}
`;
  minutesHtml += `  <div class="minute-tick minute-tick-${i}"></div>
`;
}

let html = `
<div class="hours">
${hoursHtml}
</div>
<div class="minutes">
${minutesHtml}
</div>`;

css = `/* This file was automatically generated by generator.js */
${css}`;

console.groupCollapsed("css");
console.log(css);
console.groupEnd();

console.groupCollapsed("html");
console.log(html);
console.groupEnd();
